# Site settings
name: name
email: email
url: url
description: "Assessing Dining Experiences with a Scholarly Touch"
author: "author"
title: "Epicurean Reviewer"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: username

twitter:
  username: username
