# Site settings
name: name
email: email
url: epicureanreviewer.github.io
description: "Assessing Dining Experiences with a Scholarly Touch"
author: "author"
title: "Epicurean Reviewer"
permalink: pretty
baseurl: /

# social
github:
  username: username

twitter:
  username: username
